<?php
/**
 * Created by PhpStorm.
 * User: GURU
 * Date: 2/1/2016
 * Time: 10:07 PM
 */

namespace Eureka\Services\Internal;


class Countries
{
    public static function getCountries()
    {

        $countries = array();
        $countries[] = array("iso_code"=>"AF","country_name"=>"Afghanistan","country_code"=>"93");
        $countries[] = array("iso_code"=>"AL","country_name"=>"Albania","country_code"=>"355");
        $countries[] = array("iso_code"=>"DZ","country_name"=>"Algeria","country_code"=>"213");
        $countries[] = array("iso_code"=>"AS","country_name"=>"American Samoa","country_code"=>"1");
        $countries[] = array("iso_code"=>"AD","country_name"=>"Andorra","country_code"=>"376");
        $countries[] = array("iso_code"=>"AO","country_name"=>"Angola","country_code"=>"244");
        $countries[] = array("iso_code"=>"AI","country_name"=>"Anguilla","country_code"=>"1");
        $countries[] = array("iso_code"=>"AG","country_name"=>"Antigua","country_code"=>"1");
        $countries[] = array("iso_code"=>"AR","country_name"=>"Argentina","country_code"=>"54");
        $countries[] = array("iso_code"=>"AM","country_name"=>"Armenia","country_code"=>"374");
        $countries[] = array("iso_code"=>"AW","country_name"=>"Aruba","country_code"=>"297");
        $countries[] = array("iso_code"=>"AU","country_name"=>"Australia","country_code"=>"61");
        $countries[] = array("iso_code"=>"AT","country_name"=>"Austria","country_code"=>"43");
        $countries[] = array("iso_code"=>"AZ","country_name"=>"Azerbaijan","country_code"=>"994");
        $countries[] = array("iso_code"=>"BH","country_name"=>"Bahrain","country_code"=>"973");
        $countries[] = array("iso_code"=>"BD","country_name"=>"Bangladesh","country_code"=>"880");
        $countries[] = array("iso_code"=>"BB","country_name"=>"Barbados","country_code"=>"1");
        $countries[] = array("iso_code"=>"BY","country_name"=>"Belarus","country_code"=>"375");
        $countries[] = array("iso_code"=>"BE","country_name"=>"Belgium","country_code"=>"32");
        $countries[] = array("iso_code"=>"BZ","country_name"=>"Belize","country_code"=>"501");
        $countries[] = array("iso_code"=>"BJ","country_name"=>"Benin","country_code"=>"229");
        $countries[] = array("iso_code"=>"BM","country_name"=>"Bermuda","country_code"=>"1");
        $countries[] = array("iso_code"=>"BT","country_name"=>"Bhutan","country_code"=>"975");
        $countries[] = array("iso_code"=>"BO","country_name"=>"Bolivia","country_code"=>"591");
        $countries[] = array("iso_code"=>"BA","country_name"=>"Bosnia and Herzegovina","country_code"=>"387");
        $countries[] = array("iso_code"=>"BW","country_name"=>"Botswana","country_code"=>"267");
        $countries[] = array("iso_code"=>"BR","country_name"=>"Brazil","country_code"=>"55");
        $countries[] = array("iso_code"=>"IO","country_name"=>"British Indian Ocean Territory","country_code"=>"246");
        $countries[] = array("iso_code"=>"VG","country_name"=>"British Virgin Islands","country_code"=>"1");
        $countries[] = array("iso_code"=>"BN","country_name"=>"Brunei","country_code"=>"673");
        $countries[] = array("iso_code"=>"BG","country_name"=>"Bulgaria","country_code"=>"359");
        $countries[] = array("iso_code"=>"BF","country_name"=>"Burkina Faso","country_code"=>"226");
        $countries[] = array("iso_code"=>"MM","country_name"=>"Burma Myanmar" ,"country_code"=>"95");
        $countries[] = array("iso_code"=>"BI","country_name"=>"Burundi","country_code"=>"257");
        $countries[] = array("iso_code"=>"KH","country_name"=>"Cambodia","country_code"=>"855");
        $countries[] = array("iso_code"=>"CM","country_name"=>"Cameroon","country_code"=>"237");
        $countries[] = array("iso_code"=>"CA","country_name"=>"Canada","country_code"=>"1");
        $countries[] = array("iso_code"=>"CV","country_name"=>"Cape Verde","country_code"=>"238");
        $countries[] = array("iso_code"=>"KY","country_name"=>"Cayman Islands","country_code"=>"1");
        $countries[] = array("iso_code"=>"CF","country_name"=>"Central African Republic","country_code"=>"236");
        $countries[] = array("iso_code"=>"TD","country_name"=>"Chad","country_code"=>"235");
        $countries[] = array("iso_code"=>"CL","country_name"=>"Chile","country_code"=>"56");
        $countries[] = array("iso_code"=>"CN","country_name"=>"China","country_code"=>"86");
        $countries[] = array("iso_code"=>"CO","country_name"=>"Colombia","country_code"=>"57");
        $countries[] = array("iso_code"=>"KM","country_name"=>"Comoros","country_code"=>"269");
        $countries[] = array("iso_code"=>"CK","country_name"=>"Cook Islands","country_code"=>"682");
        $countries[] = array("iso_code"=>"CR","country_name"=>"Costa Rica","country_code"=>"506");
        $countries[] = array("iso_code"=>"CI","country_name"=>"Côte d'Ivoire" ,"country_code"=>"225");
        $countries[] = array("iso_code"=>"HR","country_name"=>"Croatia","country_code"=>"385");
        $countries[] = array("iso_code"=>"CU","country_name"=>"Cuba","country_code"=>"53");
        $countries[] = array("iso_code"=>"CY","country_name"=>"Cyprus","country_code"=>"357");
        $countries[] = array("iso_code"=>"CZ","country_name"=>"Czech Republic","country_code"=>"420");
        $countries[] = array("iso_code"=>"CD","country_name"=>"Democratic Republic of Congo","country_code"=>"243");
        $countries[] = array("iso_code"=>"DK","country_name"=>"Denmark","country_code"=>"45");
        $countries[] = array("iso_code"=>"DJ","country_name"=>"Djibouti","country_code"=>"253");
        $countries[] = array("iso_code"=>"DM","country_name"=>"Dominica","country_code"=>"1");
        $countries[] = array("iso_code"=>"DO","country_name"=>"Dominican Republic","country_code"=>"1");
        $countries[] = array("iso_code"=>"EC","country_name"=>"Ecuador","country_code"=>"593");
        $countries[] = array("iso_code"=>"EG","country_name"=>"Egypt","country_code"=>"20");
        $countries[] = array("iso_code"=>"SV","country_name"=>"El Salvador","country_code"=>"503");
        $countries[] = array("iso_code"=>"GQ","country_name"=>"Equatorial Guinea","country_code"=>"240");
        $countries[] = array("iso_code"=>"ER","country_name"=>"Eritrea","country_code"=>"291");
        $countries[] = array("iso_code"=>"EE","country_name"=>"Estonia","country_code"=>"372");
        $countries[] = array("iso_code"=>"ET","country_name"=>"Ethiopia","country_code"=>"251");
        $countries[] = array("iso_code"=>"FK","country_name"=>"Falkland Islands","country_code"=>"500");
        $countries[] = array("iso_code"=>"FO","country_name"=>"Faroe Islands","country_code"=>"298");
        $countries[] = array("iso_code"=>"FM","country_name"=>"Federated States of Micronesia","country_code"=>"691");
        $countries[] = array("iso_code"=>"FJ","country_name"=>"Fiji","country_code"=>"679");
        $countries[] = array("iso_code"=>"FI","country_name"=>"Finland","country_code"=>"358");
        $countries[] = array("iso_code"=>"FR","country_name"=>"France","country_code"=>"33");
        $countries[] = array("iso_code"=>"GF","country_name"=>"French Guiana","country_code"=>"594");
        $countries[] = array("iso_code"=>"PF","country_name"=>"French Polynesia","country_code"=>"689");
        $countries[] = array("iso_code"=>"GA","country_name"=>"Gabon","country_code"=>"241");
        $countries[] = array("iso_code"=>"GE","country_name"=>"Georgia","country_code"=>"995");
        $countries[] = array("iso_code"=>"DE","country_name"=>"Germany","country_code"=>"49");
        $countries[] = array("iso_code"=>"GH","country_name"=>"Ghana","country_code"=>"233");
        $countries[] = array("iso_code"=>"GI","country_name"=>"Gibraltar","country_code"=>"350");
        $countries[] = array("iso_code"=>"GR","country_name"=>"Greece","country_code"=>"30");
        $countries[] = array("iso_code"=>"GL","country_name"=>"Greenland","country_code"=>"299");
        $countries[] = array("iso_code"=>"GD","country_name"=>"Grenada","country_code"=>"1");
        $countries[] = array("iso_code"=>"GP","country_name"=>"Guadeloupe","country_code"=>"590");
        $countries[] = array("iso_code"=>"GU","country_name"=>"Guam","country_code"=>"1");
        $countries[] = array("iso_code"=>"GT","country_name"=>"Guatemala","country_code"=>"502");
        $countries[] = array("iso_code"=>"GN","country_name"=>"Guinea","country_code"=>"224");
        $countries[] = array("iso_code"=>"GW","country_name"=>"Guinea-Bissau","country_code"=>"245");
        $countries[] = array("iso_code"=>"GY","country_name"=>"Guyana","country_code"=>"592");
        $countries[] = array("iso_code"=>"HT","country_name"=>"Haiti","country_code"=>"509");
        $countries[] = array("iso_code"=>"HN","country_name"=>"Honduras","country_code"=>"504");
        $countries[] = array("iso_code"=>"HK","country_name"=>"Hong Kong","country_code"=>"852");
        $countries[] = array("iso_code"=>"HU","country_name"=>"Hungary","country_code"=>"36");
        $countries[] = array("iso_code"=>"IS","country_name"=>"Iceland","country_code"=>"354");
        $countries[] = array("iso_code"=>"IN","country_name"=>"India","country_code"=>"91");
        $countries[] = array("iso_code"=>"ID","country_name"=>"Indonesia","country_code"=>"62");
        $countries[] = array("iso_code"=>"IR","country_name"=>"Iran","country_code"=>"98");
        $countries[] = array("iso_code"=>"IQ","country_name"=>"Iraq","country_code"=>"964");
        $countries[] = array("iso_code"=>"IE","country_name"=>"Ireland","country_code"=>"353");
        $countries[] = array("iso_code"=>"IL","country_name"=>"Israel","country_code"=>"972");
        $countries[] = array("iso_code"=>"IT","country_name"=>"Italy","country_code"=>"39");
        $countries[] = array("iso_code"=>"JM","country_name"=>"Jamaica","country_code"=>"1");
        $countries[] = array("iso_code"=>"JP","country_name"=>"Japan","country_code"=>"81");
        $countries[] = array("iso_code"=>"JO","country_name"=>"Jordan","country_code"=>"962");
        $countries[] = array("iso_code"=>"KZ","country_name"=>"Kazakhstan","country_code"=>"7");
        $countries[] = array("iso_code"=>"KE","country_name"=>"Kenya","country_code"=>"254");
        $countries[] = array("iso_code"=>"KI","country_name"=>"Kiribati","country_code"=>"686");
        $countries[] = array("iso_code"=>"XK","country_name"=>"Kosovo","country_code"=>"381");
        $countries[] = array("iso_code"=>"KW","country_name"=>"Kuwait","country_code"=>"965");
        $countries[] = array("iso_code"=>"KG","country_name"=>"Kyrgyzstan","country_code"=>"996");
        $countries[] = array("iso_code"=>"LA","country_name"=>"Laos","country_code"=>"856");
        $countries[] = array("iso_code"=>"LV","country_name"=>"Latvia","country_code"=>"371");
        $countries[] = array("iso_code"=>"LB","country_name"=>"Lebanon","country_code"=>"961");
        $countries[] = array("iso_code"=>"LS","country_name"=>"Lesotho","country_code"=>"266");
        $countries[] = array("iso_code"=>"LR","country_name"=>"Liberia","country_code"=>"231");
        $countries[] = array("iso_code"=>"LY","country_name"=>"Libya","country_code"=>"218");
        $countries[] = array("iso_code"=>"LI","country_name"=>"Liechtenstein","country_code"=>"423");
        $countries[] = array("iso_code"=>"LT","country_name"=>"Lithuania","country_code"=>"370");
        $countries[] = array("iso_code"=>"LU","country_name"=>"Luxembourg","country_code"=>"352");
        $countries[] = array("iso_code"=>"MO","country_name"=>"Macau","country_code"=>"853");
        $countries[] = array("iso_code"=>"MK","country_name"=>"Macedonia","country_code"=>"389");
        $countries[] = array("iso_code"=>"MG","country_name"=>"Madagascar","country_code"=>"261");
        $countries[] = array("iso_code"=>"MW","country_name"=>"Malawi","country_code"=>"265");
        $countries[] = array("iso_code"=>"MY","country_name"=>"Malaysia","country_code"=>"60");
        $countries[] = array("iso_code"=>"MV","country_name"=>"Maldives","country_code"=>"960");
        $countries[] = array("iso_code"=>"ML","country_name"=>"Mali","country_code"=>"223");
        $countries[] = array("iso_code"=>"MT","country_name"=>"Malta","country_code"=>"356");
        $countries[] = array("iso_code"=>"MH","country_name"=>"Marshall Islands","country_code"=>"692");
        $countries[] = array("iso_code"=>"MQ","country_name"=>"Martinique","country_code"=>"596");
        $countries[] = array("iso_code"=>"MR","country_name"=>"Mauritania","country_code"=>"222");
        $countries[] = array("iso_code"=>"MU","country_name"=>"Mauritius","country_code"=>"230");
        $countries[] = array("iso_code"=>"YT","country_name"=>"Mayotte","country_code"=>"262");
        $countries[] = array("iso_code"=>"MX","country_name"=>"Mexico","country_code"=>"52");
        $countries[] = array("iso_code"=>"MD","country_name"=>"Moldova","country_code"=>"373");
        $countries[] = array("iso_code"=>"MC","country_name"=>"Monaco","country_code"=>"377");
        $countries[] = array("iso_code"=>"MN","country_name"=>"Mongolia","country_code"=>"976");
        $countries[] = array("iso_code"=>"ME","country_name"=>"Montenegro","country_code"=>"382");
        $countries[] = array("iso_code"=>"MS","country_name"=>"Montserrat","country_code"=>"1");
        $countries[] = array("iso_code"=>"MA","country_name"=>"Morocco","country_code"=>"212");
        $countries[] = array("iso_code"=>"MZ","country_name"=>"Mozambique","country_code"=>"258");
        $countries[] = array("iso_code"=>"NA","country_name"=>"Namibia","country_code"=>"264");
        $countries[] = array("iso_code"=>"NR","country_name"=>"Nauru","country_code"=>"674");
        $countries[] = array("iso_code"=>"NP","country_name"=>"Nepal","country_code"=>"977");
        $countries[] = array("iso_code"=>"NL","country_name"=>"Netherlands","country_code"=>"31");
        $countries[] = array("iso_code"=>"AN","country_name"=>"Netherlands Antilles","country_code"=>"599");
        $countries[] = array("iso_code"=>"NC","country_name"=>"New Caledonia","country_code"=>"687");
        $countries[] = array("iso_code"=>"NZ","country_name"=>"New Zealand","country_code"=>"64");
        $countries[] = array("iso_code"=>"NI","country_name"=>"Nicaragua","country_code"=>"505");
        $countries[] = array("iso_code"=>"NE","country_name"=>"Niger","country_code"=>"227");
        $countries[] = array("iso_code"=>"NG","country_name"=>"Nigeria","country_code"=>"234");
        $countries[] = array("iso_code"=>"NU","country_name"=>"Niue","country_code"=>"683");
        $countries[] = array("iso_code"=>"NF","country_name"=>"Norfolk Island","country_code"=>"672");
        $countries[] = array("iso_code"=>"KP","country_name"=>"North Korea","country_code"=>"850");
        $countries[] = array("iso_code"=>"MP","country_name"=>"Northern Mariana Islands","country_code"=>"1");
        $countries[] = array("iso_code"=>"NO","country_name"=>"Norway","country_code"=>"47");
        $countries[] = array("iso_code"=>"OM","country_name"=>"Oman","country_code"=>"968");
        $countries[] = array("iso_code"=>"PK","country_name"=>"Pakistan","country_code"=>"92");
        $countries[] = array("iso_code"=>"PW","country_name"=>"Palau","country_code"=>"680");
        $countries[] = array("iso_code"=>"PS","country_name"=>"Palestine","country_code"=>"970");
        $countries[] = array("iso_code"=>"PA","country_name"=>"Panama","country_code"=>"507");
        $countries[] = array("iso_code"=>"PG","country_name"=>"Papua New Guinea","country_code"=>"675");
        $countries[] = array("iso_code"=>"PY","country_name"=>"Paraguay","country_code"=>"595");
        $countries[] = array("iso_code"=>"PE","country_name"=>"Peru","country_code"=>"51");
        $countries[] = array("iso_code"=>"PH","country_name"=>"Philippines","country_code"=>"63");
        $countries[] = array("iso_code"=>"PL","country_name"=>"Poland","country_code"=>"48");
        $countries[] = array("iso_code"=>"PT","country_name"=>"Portugal","country_code"=>"351");
        $countries[] = array("iso_code"=>"PR","country_name"=>"Puerto Rico","country_code"=>"1");
        $countries[] = array("iso_code"=>"QA","country_name"=>"Qatar","country_code"=>"974");
        $countries[] = array("iso_code"=>"CG","country_name"=>"Republic of the Congo","country_code"=>"242");
        $countries[] = array("iso_code"=>"RE","country_name"=>"Réunion" ,"country_code"=>"262");
        $countries[] = array("iso_code"=>"RO","country_name"=>"Romania","country_code"=>"40");
        $countries[] = array("iso_code"=>"RU","country_name"=>"Russia","country_code"=>"7");
        $countries[] = array("iso_code"=>"RW","country_name"=>"Rwanda","country_code"=>"250");
        $countries[] = array("iso_code"=>"BL","country_name"=>"Saint Barthélemy" ,"country_code"=>"590");
        $countries[] = array("iso_code"=>"SH","country_name"=>"Saint Helena","country_code"=>"290");
        $countries[] = array("iso_code"=>"KN","country_name"=>"Saint Kitts and Nevis","country_code"=>"1");
        $countries[] = array("iso_code"=>"MF","country_name"=>"Saint Martin","country_code"=>"590");
        $countries[] = array("iso_code"=>"PM","country_name"=>"Saint Pierre and Miquelon","country_code"=>"508");
        $countries[] = array("iso_code"=>"VC","country_name"=>"Saint Vincent and the Grenadines","country_code"=>"1");
        $countries[] = array("iso_code"=>"WS","country_name"=>"Samoa","country_code"=>"685");
        $countries[] = array("iso_code"=>"SM","country_name"=>"San Marino","country_code"=>"378");
        $countries[] = array("iso_code"=>"ST","country_name"=>"São Tomé and Príncipe" ,"country_code"=>"239");
        $countries[] = array("iso_code"=>"SA","country_name"=>"Saudi Arabia","country_code"=>"966");
        $countries[] = array("iso_code"=>"SN","country_name"=>"Senegal","country_code"=>"221");
        $countries[] = array("iso_code"=>"RS","country_name"=>"Serbia","country_code"=>"381");
        $countries[] = array("iso_code"=>"SC","country_name"=>"Seychelles","country_code"=>"248");
        $countries[] = array("iso_code"=>"SL","country_name"=>"Sierra Leone","country_code"=>"232");
        $countries[] = array("iso_code"=>"SG","country_name"=>"Singapore","country_code"=>"65");
        $countries[] = array("iso_code"=>"SK","country_name"=>"Slovakia","country_code"=>"421");
        $countries[] = array("iso_code"=>"SI","country_name"=>"Slovenia","country_code"=>"386");
        $countries[] = array("iso_code"=>"SB","country_name"=>"Solomon Islands","country_code"=>"677");
        $countries[] = array("iso_code"=>"SO","country_name"=>"Somalia","country_code"=>"252");
        $countries[] = array("iso_code"=>"ZA","country_name"=>"South Africa","country_code"=>"27");
        $countries[] = array("iso_code"=>"KR","country_name"=>"South Korea","country_code"=>"82");
        $countries[] = array("iso_code"=>"ES","country_name"=>"Spain","country_code"=>"34");
        $countries[] = array("iso_code"=>"LK","country_name"=>"Sri Lanka","country_code"=>"94");
        $countries[] = array("iso_code"=>"LC","country_name"=>"St. Lucia","country_code"=>"1");
        $countries[] = array("iso_code"=>"SD","country_name"=>"Sudan","country_code"=>"249");
        $countries[] = array("iso_code"=>"SR","country_name"=>"Suricountry_name","country_code"=>"597");
        $countries[] = array("iso_code"=>"SZ","country_name"=>"Swaziland","country_code"=>"268");
        $countries[] = array("iso_code"=>"SE","country_name"=>"Sweden","country_code"=>"46");
        $countries[] = array("iso_code"=>"CH","country_name"=>"Switzerland","country_code"=>"41");
        $countries[] = array("iso_code"=>"SY","country_name"=>"Syria","country_code"=>"963");
        $countries[] = array("iso_code"=>"TW","country_name"=>"Taiwan","country_code"=>"886");
        $countries[] = array("iso_code"=>"TJ","country_name"=>"Tajikistan","country_code"=>"992");
        $countries[] = array("iso_code"=>"TZ","country_name"=>"Tanzania","country_code"=>"255");
        $countries[] = array("iso_code"=>"TH","country_name"=>"Thailand","country_code"=>"66");
        $countries[] = array("iso_code"=>"BS","country_name"=>"The Bahamas","country_code"=>"1");
        $countries[] = array("iso_code"=>"GM","country_name"=>"The Gambia","country_code"=>"220");
        $countries[] = array("iso_code"=>"TL","country_name"=>"Timor-Leste","country_code"=>"670");
        $countries[] = array("iso_code"=>"TG","country_name"=>"Togo","country_code"=>"228");
        $countries[] = array("iso_code"=>"TK","country_name"=>"Tokelau","country_code"=>"690");
        $countries[] = array("iso_code"=>"TO","country_name"=>"Tonga","country_code"=>"676");
        $countries[] = array("iso_code"=>"TT","country_name"=>"Trinidad and Tobago","country_code"=>"1");
        $countries[] = array("iso_code"=>"TN","country_name"=>"Tunisia","country_code"=>"216");
        $countries[] = array("iso_code"=>"TR","country_name"=>"Turkey","country_code"=>"90");
        $countries[] = array("iso_code"=>"TM","country_name"=>"Turkmenistan","country_code"=>"993");
        $countries[] = array("iso_code"=>"TC","country_name"=>"Turks and Caicos Islands","country_code"=>"1");
        $countries[] = array("iso_code"=>"TV","country_name"=>"Tuvalu","country_code"=>"688");
        $countries[] = array("iso_code"=>"UG","country_name"=>"Uganda","country_code"=>"256");
        $countries[] = array("iso_code"=>"UA","country_name"=>"Ukraine","country_code"=>"380");
        $countries[] = array("iso_code"=>"AE","country_name"=>"United Arab Emirates","country_code"=>"971");
        $countries[] = array("iso_code"=>"GB","country_name"=>"United Kingdom","country_code"=>"44");
        $countries[] = array("iso_code"=>"US","country_name"=>"United States","country_code"=>"1");
        $countries[] = array("iso_code"=>"UY","country_name"=>"Uruguay","country_code"=>"598");
        $countries[] = array("iso_code"=>"VI","country_name"=>"US Virgin Islands","country_code"=>"1");
        $countries[] = array("iso_code"=>"UZ","country_name"=>"Uzbekistan","country_code"=>"998");
        $countries[] = array("iso_code"=>"VU","country_name"=>"Vanuatu","country_code"=>"678");
        $countries[] = array("iso_code"=>"VA","country_name"=>"Vatican City","country_code"=>"39");
        $countries[] = array("iso_code"=>"VE","country_name"=>"Venezuela","country_code"=>"58");
        $countries[] = array("iso_code"=>"VN","country_name"=>"Vietnam","country_code"=>"84");
        $countries[] = array("iso_code"=>"WF","country_name"=>"Wallis and Futuna","country_code"=>"681");
        $countries[] = array("iso_code"=>"YE","country_name"=>"Yemen","country_code"=>"967");
        $countries[] = array("iso_code"=>"ZM","country_name"=>"Zambia","country_code"=>"260");
        $countries[] = array("iso_code"=>"ZW","country_name"=>"Zimbabwe","country_code"=>"263");

        return $countries;
    }
}